#!/bin/bash
echo "📄 Starting Level 2 Challenge..."

echo "1. Create three files:"
echo "   touch document.txt notes.md data.csv"
echo ""
echo "2. Copy document.txt to document_backup.txt:"
echo "   cp document.txt document_backup.txt"
echo ""
echo "3. Rename notes.md to important_notes.md:"
echo "   mv notes.md important_notes.md"
echo ""
echo "4. Create a directory structure:"
echo "   mkdir -p projects/{website,scripts,docs}"
echo ""
echo "5. Move data.csv to projects/docs/:"
echo "   mv data.csv projects/docs/"
echo ""
echo "6. View the contents of document.txt:"
echo "   cat document.txt"
echo ""
echo "7. Safely remove document_backup.txt:"
echo "   rm -i document_backup.txt"
