#!/bin/bash
echo "🔒 Starting Level 4 Challenge..."

echo "1. Check your current user:"
echo "   whoami"
echo "   id"
echo ""
echo "2. View detailed file listing:"
echo "   ls -l"
echo ""
echo "3. Create a script and make it executable:"
echo "   echo '#!/bin/bash' > myscript.sh"
echo "   echo 'echo \"Hello World\"' >> myscript.sh"
echo "   chmod +x myscript.sh"
echo "   ls -l myscript.sh"
echo ""
echo "4. View running processes:"
echo "   ps aux | head -10"
echo ""
echo "5. Check system resources:"
echo "   free -h"
echo "   df -h"
echo ""
echo "6. Monitor processes interactively:"
echo "   top"
echo "   (press 'q' to quit)"
